// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

declare global {
  interface Window {
    __RUNTIME_CONFIG__?: Record<string, string | undefined>;
  }
}

const env = import.meta.env;
const runtimeConfig = typeof window !== 'undefined' ? window.__RUNTIME_CONFIG__ ?? {} : {};
const read = (...values: Array<string | undefined>) =>
  values.map((v) => (v ?? '').trim()).find((v) => !!v) ?? '';

const SUPABASE_PROJECT_ID = read(runtimeConfig.VITE_SUPABASE_PROJECT_ID, env.VITE_SUPABASE_PROJECT_ID);
const SUPABASE_URL =
  read(runtimeConfig.VITE_SUPABASE_URL, env.VITE_SUPABASE_URL, env.VITE_SUPABASE_PROJECT_URL) ||
  (SUPABASE_PROJECT_ID ? `https://${SUPABASE_PROJECT_ID}.supabase.co` : '');
const SUPABASE_PUBLISHABLE_KEY = read(
  runtimeConfig.VITE_SUPABASE_PUBLISHABLE_KEY,
  runtimeConfig.VITE_SUPABASE_ANON_KEY,
  env.VITE_SUPABASE_PUBLISHABLE_KEY,
  env.VITE_SUPABASE_ANON_KEY,
  env.VITE_SUPABASE_KEY,
);

const hasPlaceholder = (value: string) =>
  /(your_|example|invalid-project-ref|invalid-publishable-key)/i.test(value);

export const supabaseConfigError =
  !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? 'Missing env vars: set VITE_SUPABASE_URL (or VITE_SUPABASE_PROJECT_ID) and VITE_SUPABASE_PUBLISHABLE_KEY.'
    : hasPlaceholder(SUPABASE_URL) || hasPlaceholder(SUPABASE_PUBLISHABLE_KEY)
      ? 'Supabase env vars contain placeholder values.'
      : null;

export const isSupabaseConfigured = !supabaseConfigError;

if (supabaseConfigError) {
  console.error(`[Supabase] ${supabaseConfigError}`);
}

const EFFECTIVE_SUPABASE_URL = SUPABASE_URL || 'https://invalid-project-ref.supabase.co';
const EFFECTIVE_SUPABASE_PUBLISHABLE_KEY = SUPABASE_PUBLISHABLE_KEY || 'invalid-publishable-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(EFFECTIVE_SUPABASE_URL, EFFECTIVE_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
